import React, { useState } from 'react';
import { Goal, Task, ReasoningStep, IntegrationStatus } from '../types';
import { breakDownGoal } from '../services/geminiService';

interface PlannerProps {
  goals: Goal[];
  setGoals: React.Dispatch<React.SetStateAction<Goal[]>>;
  tasks: Task[];
  setTasks: React.Dispatch<React.SetStateAction<Task[]>>;
  hasIntegrations: boolean;
  integrations: IntegrationStatus;
  toggleIntegration: (key: keyof IntegrationStatus) => void;
}

const Planner: React.FC<PlannerProps> = ({ goals, setGoals, tasks, setTasks, hasIntegrations, integrations, toggleIntegration }) => {
  const [input, setInput] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [reasoning, setReasoning] = useState<ReasoningStep[]>([]);

  const handleCreatePlan = async () => {
    if (!input) return;
    setIsProcessing(true);
    setReasoning([
      { id: '1', action: 'Analyzing high-level goal...', status: 'processing' },
      { id: '2', action: hasIntegrations ? 'Syncing External Tools (Cal/Fit)...' : 'Skipping Tool Sync (Not Connected)', status: 'pending' },
      { id: '3', action: 'Synthesizing executable sub-tasks...', status: 'pending' },
    ]);

    try {
      await new Promise(r => setTimeout(r, 1000));
      setReasoning(prev => prev.map((s, i) => i === 0 ? { ...s, status: 'done' } : i === 1 ? { ...s, status: 'processing' } : s));

      await new Promise(r => setTimeout(r, 800));
      setReasoning(prev => prev.map((s, i) => i === 1 ? { ...s, status: 'done' } : i === 2 ? { ...s, status: 'processing' } : s));

      const constraints = hasIntegrations ? "Integrations enabled: Prioritize recovery and avoid meeting clashes." : "No integrations: standard schedule.";
      const today = new Date().toISOString().split('T')[0];
      const newTasks = await breakDownGoal(input, constraints, hasIntegrations);

      // Add dueDate to new tasks
      const tasksWithDates = newTasks.map(task => ({
        ...task,
        dueDate: today
      }));

      const newGoal: Goal = {
        id: Math.random().toString(),
        title: input,
        description: "Generated by LifeLoop AI",
        deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        tasks: tasksWithDates,
        status: 'active'
      };

      setGoals(prev => [...prev, newGoal]);
      setTasks(prev => [...prev, ...tasksWithDates]);
      setReasoning(prev => prev.map(s => ({ ...s, status: 'done' })));
      setInput('');
    } catch (err) {
      console.error(err);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <section className="glass p-8 rounded-3xl">
        <h2 className="text-3xl font-bold mb-6">Autonomous Planning</h2>
        <div className="flex gap-4">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Tell LifeLoop what you want to achieve..."
            className="flex-1 bg-slate-900 border border-white/10 rounded-2xl px-6 py-4 focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
            disabled={isProcessing}
          />
          <button
            onClick={handleCreatePlan}
            disabled={isProcessing || !input}
            className="bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-700 px-8 py-4 rounded-2xl font-bold transition-all shadow-lg shadow-indigo-500/20"
          >
            {isProcessing ? 'Agent Thinking...' : 'Plan It'}
          </button>
        </div>
      </section>

      {(isProcessing || reasoning.length > 0) && (
        <section className="glass p-8 rounded-3xl border-indigo-500/30 border">
          <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4">Reasoning Loop</h3>
          <div className="space-y-4">
            {reasoning.map(step => (
              <div key={step.id} className="flex items-center gap-4">
                <div className={`w-3 h-3 rounded-full ${step.status === 'done' ? 'bg-emerald-500' : step.status === 'processing' ? 'bg-amber-500 animate-pulse' : 'bg-slate-700'}`} />
                <span className={step.status === 'done' ? 'text-slate-300' : 'text-slate-500'}>{step.action}</span>
              </div>
            ))}
          </div>
        </section>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {goals.map(goal => (
          <div key={goal.id} className="glass p-6 rounded-3xl border border-white/5">
            <h3 className="text-xl font-bold mb-2">{goal.title}</h3>
            <div className="flex justify-between items-center text-sm text-slate-500">
              <span>{goal.tasks.length} tasks scheduled</span>
              <span className="bg-indigo-500/10 text-indigo-400 px-2 py-0.5 rounded uppercase font-bold text-xs">{goal.status}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Planner;
